frontend:
  image: uneasyyang001/frontend
  tag: 06a5828
  autoscaling:
    averageUtilization: 90
backend:
  image: uneasyyang001/backend
  tag: 06a5828
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
